# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295cd13a164b07ce6a595241ebd72e48936ed57c3b352ec11e9857a1dd85d65c6573e22c7941200181449b25ea9e12b69b621ed567512cd66c4c23d195feea33

test:
  secret_key_base: 26ebe257fd3e62dc3e2778315ccc7418722bfa082fc66ca1c63d857d08a19c842a5e1bec2ba823a5746c13c8969e1db8b2965a7a627eae312d7955fdee78015a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
